export const BASE_URL = 'http://localhost:3000';

export const countries = [
  { name: 'Albania' },
  { name: 'Argentina' },
  { name: 'Austria' },
  { name: 'Australia' },
  { name: 'Azerbaijan' },
  { name: 'Bosnia and Herzegovina' },
  { name: 'Barbados' },
  { name: 'Bangladesh' },
  { name: 'Belgium' },
  { name: 'Burkina Faso' },
  { name: 'Bulgaria' },
  { name: 'Bolivia' },
  { name: 'Brazil' },
  { name: 'Canada' },
  { name: 'Switzerland' },
  { name: 'Chile' },
  { name: 'Cameroon' },
  { name: 'China' },
  { name: 'Colombia' },
  { name: 'Costa Rica' },
  { name: 'Cuba' },
  { name: 'Cyprus' },
  { name: 'Czech Republic' },
  { name: 'Germany' },
  { name: 'Denmark' },
  { name: 'Ecuador' },
  { name: 'Estonia' },
  { name: 'Egypt' },
  { name: 'Spain' },
  { name: 'Finland' },
  { name: 'France' },
  { name: 'United Kingdom' },
  { name: 'Georgia' },
  { name: 'Greece' },
  { name: 'Hong Kong' },
  { name: 'Croatia' },
  { name: 'Hungary' },
  { name: 'Indonesia' },
  { name: 'Ireland' },
  { name: 'Israel' },
  { name: 'India' },
  { name: 'Iraq' },
  { name: 'Iceland' },
  { name: 'Italy' },
  { name: 'Jamaica' },
  { name: 'Japan' },
  { name: 'Kuwait' },
  { name: 'Kazakhstan' },
  { name: 'Lithuania' },
  { name: 'Luxembourg' },
  { name: 'Latvia' },
  { name: 'Libya' },
  { name: 'Morocco' },
  { name: 'Montenegro' },
  { name: 'Malta' },
  { name: 'Maldives' },
  { name: 'Mexico' },
  { name: 'Netherlands' },
  { name: 'Norway' },
  { name: 'New Zealand' },
  { name: 'Peru' },
  { name: 'Philippines' },
  { name: 'Pakistan' },
  { name: 'Poland' },
  { name: 'Portugal' },
  { name: 'Qatar' },
  { name: 'Romania' },
  { name: 'Russia' },
  { name: 'Serbia' },
  { name: 'Saudi Arabia' },
  { name: 'Sweden' },
  { name: 'Slovenia' },
  { name: 'Slovakia' },
  { name: 'Turkey' },
  { name: 'United States' },
  { name: 'Ukraine' },
];